apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        denglanlan/deng-test-three: true
        denglanlan/jx-quick: true
        denglanlan/k8s-jx3: true
        denglanlan/php-helloworld: true
        denglanlan/test-jx3: true
        denglanlan/test-two: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        denglanlan/deng-test-three: merge
        denglanlan/jx-quick: merge
        denglanlan/k8s-jx3: merge
        denglanlan/php-helloworld: merge
        denglanlan/test-jx3: merge
        denglanlan/test-two: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - denglanlan/k8s-jx3
        - denglanlan/deng-test-three
        - denglanlan/jx-quick
        - denglanlan/php-helloworld
        - denglanlan/test-jx3
        - denglanlan/test-two
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - denglanlan/k8s-jx3
        - denglanlan/deng-test-three
        - denglanlan/jx-quick
        - denglanlan/php-helloworld
        - denglanlan/test-jx3
        - denglanlan/test-two
      target_url: http://dashboard-jx.jx3.sky-cloud.net
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
