apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: denglanlan
    provider: https://github.com
    providerKind: github
    repositories:
    - name: deng-test-jx3
    scheduler: in-repo
